Repository sopra-fs22-group-15/cozycave-client, pull requests merged in 2022-05, with the labels that each got.

#56 removed console.log of request body when sending request
  src/RegisterForm.js
Labels: bug

#59 Changed login request body to have the correct fields.
  src/LoginForm.js
Labels: bug

#65 Heroku deploy test.
  src/App.js
Labels: bug

#108 Feature/my applications
  src/App.js
  src/components/listings/ListingElement.js
  src/components/listings/ListingList.js
  src/components/profile/applications/ProfileApplications.js
  src/components/profile/applications/ProfileApplicationsElement.js
  src/components/profile/applications/ProfileApplicationsList.js
  src/components/profile/listings/ProfileListings.js
  src/components/profile/listings/ProfileListingsElement.js
  src/components/profile/listings/ProfileListingsList.js
  src/components/util/mockApplicationsFromOneUser.js
  src/components/util/mockListings.js
Labels: feature

#111 added form field for phone number in profile details.
  package-lock.json
  package.json
  src/components/profile/ProfileDetails.js
Labels: enhancement, priority:high

#110 Feature/edit listing
  src/App.js
  src/components/crud/EditListing.js
  src/components/profile/listings/ProfileListingsElement.js
  src/components/util/mockListings.js
  src/styles/EditListing.scss
Labels: feature, priority:critical

#109 Feature/photo upload
  package-lock.json
  package.json
  src/components/crud/CreateAd.js
  src/components/listings/ImageCarousel.js
  src/styles/CreateAd.scss
Labels: feature, priority:critical

#112 added map display to listings
  package-lock.json
  src/AdOverviewPage.js
  src/components/util/mockListings.js
Labels: feature

#113 connect backend
  src/AdOverviewPage.js
  src/App.js
  src/LoginForm.js
  src/RegisterForm.js
  src/ResultsPage.js
  src/components/crud/CreateAd.js
  src/components/layout/Navbar.js
  src/components/listings/ListingList.js
  src/components/profile/ProfileDetails.js
  src/components/profile/ProfilePage.js
  src/components/profile/listings/ProfileListings.js
  src/components/profile/listings/ProfileListingsElement.js
  src/components/profile/listings/ProfileListingsList.js
  src/components/schemas/Address.js
  src/components/schemas/Listing.js
  src/components/util/addressCreator.js
  src/helpers/api.js
Labels: bug, priority:critical

#114 fix/backend-connection-401-error
  src/helpers/api.js
Labels: bug

#115 Feature/calculate timing
  src/AdOverviewPage.js
  src/ResultsPage.js
  src/helpers/decideGender.js
  src/helpers/getDomain.js
Labels: feature, priority:critical

#116 Enhancement/login register context
  src/App.js
  src/LoginForm.js
  src/RegisterForm.js
  src/components/layout/Navbar.js
  src/components/profile/ProfilePage.js
  src/context/auth-context.js
Labels: enhancement, priority:critical

#117 centered results in center of screen for different device sizes
  src/ResultsPage.js
  src/index.css
  src/styles/Listings.scss
  src/styles/ResultsPage.scss
Labels: bug, priority:high

#118 Added reset password page, functionality
  package-lock.json
  src/LoginForm.js
  src/ResetPasswordForm.js
  src/components/layout/Navbar.js
  src/context/login-context.js
Labels: feature, priority:critical

#121 fixed navbar not displaying correctly on other pages than overview.
  src/components/layout/Navbar.js
  src/helpers/getDomain.js
  src/styles/Navbar.scss
Labels: bug, priority:critical

#122 Connected MyApplications and MyListings to backend, fixed ad overview…
  src/AdOverviewPage.js
  src/components/layout/Navbar.js
  src/components/profile/applications/ProfileApplications.js
  src/components/profile/applications/ProfileApplicationsElement.js
  src/components/profile/listings/ProfileListingsElement.js
  src/helpers/getDomain.js
Labels: bug, enhancement, priority:critical

#126 Feature/gather together
  src/App.js
  src/GatherTogetherPage.js
  src/LandingPage.js
  src/ResultsPage.js
  src/components/layout/Navbar.js
  src/components/util/mockParticipants.js
  src/context/gather-context.js
Labels: feature, design

#127 Enhancement/filter listings
  package-lock.json
  package.json
  src/App.js
  src/ResultsPage.js
  src/components/crud/CreateAd.js
  src/components/layout/Navbar.js
  src/components/listings/ListingList.js
  src/components/util/addressCreator.js
  src/components/util/priceRangeBuilder.js
  src/components/util/queryStringBuilder.js
  src/context/filter-context.js
  src/styles/Navbar.scss
Labels: enhancement, feature, priority:critical

#128 fixed travel time calculation, gather together button
  src/AdOverviewPage.js
  src/GatherTogetherPage.js
  src/components/layout/Navbar.js
  src/helpers/getDomain.js
Labels: bug

#129 Fix/image upload
  src/RegisterForm.js
  src/components/crud/CreateAd.js
  src/components/profile/ProfileDetails.js
  src/components/util/getGenderOptions.js
  src/styles/ProfilePage.scss
Labels: priority:critical

#134 Fix/gather together and applications
  src/AdOverviewPage.js
  src/App.js
  src/GatherTogetherPage.js
  src/components/layout/Navbar.js
  src/components/profile/ForeignViewProfile.js
  src/components/profile/applications/ProfileApplicationsElement.js
  src/components/profile/listings/ProfileListingsElement.js
  src/context/gather-context.js
Labels: bug

#135 Feature/web sockets
  package-lock.json
  src/GatherTogetherPage.js
Labels: feature, priority:critical

#136 fixed display bug
  src/components/profile/ForeignViewProfile.js
Labels: bug

#137 Fix/listing image upload
  src/AdOverviewPage.js
  src/App.js
  src/ResultsPage.js
  src/components/crud/CreateAd.js
  src/components/layout/Navbar.js
  src/components/listings/ListingList.js
  src/components/profile/ProfileDetails.js
  src/components/profile/listings/ProfileListings.js
  src/components/profile/listings/ProfileListingsElement.js
  src/context/auth-context.js
  src/helpers/displayPictures.js
  src/helpers/getDomain.js
  src/styles/Listings.scss
Labels: bug, enhancement, priority:critical

#138 Feature/gather forms
  package-lock.json
  src/App.js
  src/GatherTogetherPage.js
  src/components/layout/Navbar.js
  src/components/profile/ForeignViewProfile.js
  src/components/profile/GatherTogetherDetails.js
  src/components/profile/GatherTogetherRequest.js
  src/context/gather-context.js
Labels: bug, enhancement

#139 Feature/gather forms
  src/AdOverviewPage.js
  src/App.js
  src/GatherTogetherPage.js
  src/components/profile/GatherTogetherDetails.js
  src/components/profile/GatherTogetherRequest.js
  src/context/gather-context.js
  src/helpers/getDomain.js
Labels: bug, enhancement

#140 Removed unneeded buttons
  src/AdOverviewPage.js
  src/LoginForm.js
Labels: bug

#141 Added ReadMe, getUser fix
  src/App.js
  src/ReadMe.js
  src/components/layout/Navbar.js
Labels: documentation, priority:medium

#142 Fix/listing crud
  package-lock.json
  package.json
  public/index.html
  src/AdOverviewPage.js
  src/App.js
  src/RegisterForm.js
  src/ResultsPage.js
  src/components/crud/CreateAd.js
  src/components/crud/EditListing.js
  src/components/layout/Navbar.js
  src/components/listings/ListingList.js
  src/components/profile/ProfileDetails.js
  src/components/profile/ProfilePage.js
  src/components/profile/listings/ProfileListingsElement.js
  src/components/profile/listings/ProfileListingsList.js
  src/components/util/getGenderOptions.js
  src/helpers/decideGender.js
  src/styles/CreateAd.scss
  src/styles/EditListing.scss
Labels: bug, enhancement, feature, priority:critical

#143 added search filter and fixed special address bug profile page
  src/App.js
  src/RegisterForm.js
  src/SearchBar.js
  src/components/layout/Navbar.js
  src/components/listings/ListingList.js
  src/components/profile/ProfileDetails.js
  src/components/util/queryStringBuilder.js
  src/context/filter-context.js
Labels: bug, enhancement, priority:critical

#145 removed logging, fixed 2nd address display
  package-lock.json
  src/AdOverviewPage.js
  src/App.js
  src/GatherTogetherPage.js
  src/RegisterForm.js
Labels: bug

#144 fixed gender display on ad overview
  public/assets/cozy_cave_logo_v1.svg
  src/App.js
  src/LandingPage.js
  src/SearchBar.js
  src/helpers/decideGender.js
  src/helpers/getDomain.js
Labels: bug
